### ISSUE TITLE
项目融合请求

### ISSUE THREAD

**Issue by muhanstudio** [IAliceBobI/sy-httpget-widget#1]
你好，本来之前在写一个类似的挂件，但是废弃了，今天翻新准备从做，发现集市里已经有类似挂件，所以打算直接交给您融合，预览视频以及项目源码如下

https://github.com/IAliceBobI/sy-httpget-widget/assets/29907393/7658159d-1bf1-440c-a547-fb2b5b5d3965

[postman-html.zip](https://github.com/IAliceBobI/sy-httpget-widget/files/13349094/postman-html.zip)

**Comment by IAliceBobI** [comment]
> 你好，本来之前在写一个类似的挂件，但是废弃了，今天翻新准备从做，发现集市里已经有类似挂件，所以打算直接交给您融合，预览视频以及项目源码如下
> 
>  1699966346563.-.Trim.mp4 
> [postman-html.zip](https://github.com/IAliceBobI/sy-httpget-widget/files/13349094/postman-html.zip)


感谢您的支持，录视频辛苦了！


您这个类似postman的，功能比较多。搞的也比我那个简单的好。跟我的融合了，可惜了。不如开一个新项目。


我那个主要的想法是往小了做，当成按钮，放在内容中，尽量不占地方。
功能也是只get一下，用于配合后端服务。
主要是给会写后端服务的同学提供方便、提供一个思路。


你的主要是做http协议细节的一个检视，应该是两个不同的widget。


如果要融合，也是搞个插件项目，比如 `widget工厂` 可以插入各种不同的 widget，比如你这种的，或者我那种模仿按钮的。
widget以 思源里面的 html块 的形式出现。 插件工厂提供siyuan客户端放入globalthis, 给各种 html块 widget 使用。
